StoreWeapon/Models/StoreController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using BLL.BLM;
using StoreWeapon.Models;

namespace StoreWeapon.Controllers
{
    namespace StoreWeapon.Controllers
    {
        public class StoreController : Controller
        {

            // GET: Store
            public ActionResult Index()
            {
                //TODO Automapping
                ViewBag.category = (Request.QueryString["Category"] ?? "All").Replace(" ",String.Empty);
                TempData["Category"] = ViewBag.category;
                //return View(ParserKnifeSingleTon.GetInstance().Knifes);
                var knivesForStore = new KnifeManager().GetKnivesByCategory(new string[] {ViewBag.category})
                    .Select(knife => new KnifeForStore
                    {
                        Id  = knife.GuidKnife,
                        Category = knife.Category,
                        Description = knife.Description,
                        LogoPath = knife.LogoPath,
                        Name = knife.Name,
                        NewPrice = knife.NewPrice,
                        OldPrice = knife.OldPrice
                    })
                    .ToList();

                return View(knivesForStore);
            }


            public PartialViewResult _WeaponList(string[] categories)
            {
               
                var knivesForStore = new KnifeManager().GetKnivesByCategory(categories)
                    .Select(knife => new KnifeForStore
                    {
                        Id = knife.GuidKnife,
                        Category = knife.Category,
                        Description = knife.Description,
                        LogoPath = knife.LogoPath,
                        Name = knife.Name,
                        NewPrice = knife.NewPrice,
                        OldPrice = knife.OldPrice
                    })
                    .ToList();

                return PartialView(knivesForStore);
                //return PartialView( (category == "All") ? ParserKnifeSingleTon.GetInstance().Knifes: ParserKnifeSingleTon.GetInstance().Categories.Find(x => x.CategoryName == category).KnifeList);
            }

            public PartialViewResult _CategoriesPanel(string newCategory)
            {
  
                var categories = from faq in new KnifeManager().GetAllKnifesList() group faq by faq.Category into faqGroup select faqGroup;
                var category = categories.Select(cat => new StoreCategory() {Name = cat.Key, Count = cat.Count()}).ToList();

                //var res = new KnifeManager().getAllKnifesList()
                //    .SelectMany(x => x.Category, count => new {nameCategory, count}).Distinct()
                //    .Select(x => new {a = x.nameCategory, b = x.count});

                //foreach (var result in res)
                //{
                //    Console.WriteLine("Name: {0}, Count: {1}", result.Name, result.Count);
                //}
                return PartialView("_CategoriesPanel", category);
            }
        }
    }
}

StoreWeapon/Views/Shared/_Header.cshtml
 <!--HEADER INNER START -->
<header class="innerHeader isStickyInner">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-sm-2">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")"><img src="~/Content/images/cutss-logo.png" alt=""></a>
                </div>
            </div>
            <div class="col-sm-7">
                <nav class="mainNav2">
                    <div class="mobileMenu2">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <ul>
                        <li class="has-menu-items active">
                            @Html.ActionLink("Главная", "Index","Home")                          
                        </li>
                        <li class="has-menu-items">
                            @Html.ActionLink("Вопросы-Ответы", "About", "Home")                           
                        </li>                      
                        <li>
                            @Html.ActionLink("Ножы", "Index", "Home")
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-1 col-sm-3">
                <div class="sicialIcon">
                    <img src="~/Content/images/iconCard.png" />
                    <div >0</div>
                    @*<div id="countKnives">0</div>*@
                </div>
            </div>
            <div class="col-lg-2 col-sm-3">
                <div class="sicialIcon">
                    <a class="fb" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="tw" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="gp" href="#"><i class="fa fa-google-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
</header>
<!--HEADER INNER END -->

StoreWeapon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include All CSS -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/settings.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/owl.carousel.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/owl.theme.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/select2.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/preset.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/responsive.css" />
    <link rel="stylesheet" id="layout" href="~/Content/css/lay_colors/wide.css">
    <link rel="stylesheet" id="lightDark" href="~/Content/css/lay_colors/dark.css">
    <link rel="stylesheet" id="colorChem" href="~/Content/css/lay_colors/color1.css">
    <!-- End Include All CSS -->
   
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="~/Content/images/favicon.png">
 </head>
<body>


    @{
        Html.RenderPartial("_Header");
    }

    @RenderBody()

    <!--FOOTER START-->
    <footer class="footer overlay90" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <aside class="widget">
                        <h3 class="widgetTitle">Our Contacts</h3>
                        <address class="faddress">
                            <div class="sads">
                                <i class="fa fa-globe"></i>
                                <p>....... street ....</p>
                                <p>......, ......., .....</p>
                            </div>
                            <div class="sads">
                                <i class="fa fa-phone"></i>
                                <p>..................., .............</p>
                            </div>
                            <div class="sads">
                                <i class="fa fa-envelope-o"></i>
                                <p class="fmail"><a href="">*****************</a></p>
                            </div>
                        </address>
                    </aside>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <aside class="widget">
                        <h3 class="widgetTitle">Working Hours</h3>
                        <ul class="workHour">
                            <li>Monday - Friday <span>9:00 - 17:00</span></li>
                            <li>Saturday <span>9:00 - 20:00</span></li>
                            <li>Sunday <span>10:00 - 15:00</span></li>
                        </ul>
                    </aside>
                </div>
                <div class="clearfix hidden-lg hidden-md"></div>
            </div>
        </div>
    </footer>
    <!--FOOTER END-->

    <script type="text/javascript" src="~/Content/js/sort.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery-ui.js"></script>

    <script type="text/javascript" src="~/Content/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.themepunch.revolution.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="~/Content/js/owl.carousel.js"></script>
    
    <script type="text/javascript" src="~/Content/js/gmaps.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.appear.js"></script>
    <script type="text/javascript" src="~/Content/js/select2.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.magnific-popup.js"></script>
    <script type="text/javascript" src="~/Content/js/theme.js"></script>



    <script>

    ////////////////////////////ADD TO CART////////////////////////

    $(window).load(function () {

        $("#countKnives").text(new cookieList("Knifes").items().length);
        //TODO DUBLICATE CODE REMOVE THIS, CALLBACK AJAX COPY
        $(".cartButton").on("click", function (item) {
            var list = new cookieList("Knifes");
            list.add(item.target.getAttribute('id'));
            $("#countKnives").text(list.items().length);
        });
    });


    var cookieList = function(cookieName) {
    var cookie = $.cookie(cookieName);
        var items = cookie ? cookie.split(/,/) : new Array();

        return {
            "add": function(val) {
                items.push(val);
                $.cookie(cookieName, items.join(','), { expires: 3});
            },
            "remove": function (val) {
                indx = items.indexOf(val);
                if(indx!=-1) items.splice(indx, 1);
                $.cookie(cookieName, items.join(','));        },
            "clear": function() {
                items = null;
                $.cookie(cookieName, null);
            },
            "items": function() {
                return items;
            }
        }
    }
    
    ////////////////////////////END ADD TO CART//////////////////////


    /////////////////////////////// CATEGORY SELECT////////////////////////////////

    $('.linkCategory').on('click',
        function(item) {
            jQuery.ajaxSettings.traditional = true;
            var selectid = item.target.childNodes[0].data.replace(/\s/g, '');
            var selected = $(("#" + selectid)).attr("class");
            if (selected === "fa fa-check") {
                $(("#" + selectid)).attr("class", " ");
            } else {
                $(("#" + selectid)).attr("class", "fa fa-check");
            }
            var cat = [];
             $("i.fa.fa-check").each(function() {
                cat.push($(this).attr("id"));
            });



            $.ajax({
                url: "@(Url.Action("_WeaponList", "Store"))",
                type: "GET",
                cache: false,
                async: true,
                data: {
                    categories: cat },
                success: function (result) {
                    $("#listWeapons").html(result);

                    $(".cartButton").on("click", function (item) {
                        var list = new cookieList("Knifes");
                        list.add(item.target.getAttribute('id'));
                        $("#countKnives").text(list.items().length);
                    });
                }
            });

        });
    /////////////////////////////// END CATEGORY SELECT////////////////////////////////
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquerycookie")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>